# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "your-client-id" # This will be auto-updated by CLI
name = "GiftCart: Gift with purchase"
handle = "gift-cart-bot"
application_url = "https://nonidiomatic-verda-direly.ngrok-free.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "your-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Scopes for orders, customers, and logic
scopes = "write_products,read_products,write_customers,read_customers,write_orders,read_orders,write_discounts,read_discounts,write_cart_transforms,read_cart_transforms,read_themes"

[auth]
redirect_urls = [
  "https://shopify.com/auth/callback",
  "https://shopify.com/auth/shopify/callback",
  "https://shopify.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false

[app_proxy]
url = "https://nonidiomatic-verda-direly.ngrok-free.dev"
subpath = "advanced-cart-bot"
prefix = "apps"
